# Generated by Django 4.2.2 on 2023-06-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_boardtb_brd_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/", verbose_name="uploaded file"
                    ),
                ),
                (
                    "brd_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.boardtb"
                    ),
                ),
            ],
        ),
    ]
