# Generated by Django 4.2.2 on 2023-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_uploadfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(upload_to="board/", verbose_name="uploaded file"),
        ),
    ]
