# Generated by Django 4.2.2 on 2023-06-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CenterTB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cent_name",
                    models.CharField(max_length=10, verbose_name="center name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VOCTB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voc_file",
                    models.FileField(upload_to="voc/", verbose_name="uploaded file"),
                ),
                (
                    "cent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voc.centertb"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerTB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "cust_name",
                    models.CharField(max_length=30, verbose_name="customer name"),
                ),
                (
                    "declaration",
                    models.CharField(max_length=300, verbose_name="additional info"),
                ),
                (
                    "cust_type",
                    models.CharField(max_length=10, verbose_name="customer type"),
                ),
                (
                    "cust_num",
                    models.CharField(
                        max_length=11, verbose_name="customer phone number"
                    ),
                ),
                (
                    "cust_ads",
                    models.CharField(max_length=30, verbose_name="customer address"),
                ),
                (
                    "is_tm",
                    models.BooleanField(default=False, verbose_name="check TM status"),
                ),
                ("is_answer", models.BooleanField(verbose_name="check TM answer")),
                (
                    "voc_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voc.voctb"
                    ),
                ),
            ],
        ),
    ]
