# Generated by Django 4.2.2 on 2023-06-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centertb",
            name="cent_name",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="center name"
            ),
        ),
    ]
