# Generated by Django 4.2.2 on 2023-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0004_voctb_uploaded_at_voctb_voc_desc_alter_voctb_cent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customertb",
            name="cust_type",
        ),
        migrations.AddField(
            model_name="customertb",
            name="cust_importance",
            field=models.BooleanField(
                default=0, verbose_name="customer level. 0: normal, 1: emergency"
            ),
        ),
        migrations.AddField(
            model_name="customertb",
            name="tm_judge",
            field=models.CharField(
                default=None, max_length=50, verbose_name="TM messages"
            ),
        ),
        migrations.AddField(
            model_name="customertb",
            name="tm_result",
            field=models.BooleanField(default=False, verbose_name="check TM result"),
        ),
        migrations.AlterField(
            model_name="customertb",
            name="is_answer",
            field=models.BooleanField(default=False, verbose_name="check TM answer"),
        ),
        migrations.AlterField(
            model_name="customertb",
            name="receipt",
            field=models.DateTimeField(verbose_name="date joined"),
        ),
        migrations.AlterField(
            model_name="voctb",
            name="voc_file",
            field=models.FileField(
                upload_to="voc/%Y/%m/%d", verbose_name="uploaded file"
            ),
        ),
    ]
