# Generated by Django 4.2.2 on 2023-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0005_remove_customertb_cust_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voctb",
            name="voc_desc",
            field=models.CharField(blank=True, max_length=20, verbose_name="file name"),
        ),
    ]
