# Generated by Django 4.2.2 on 2023-06-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0006_alter_voctb_voc_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voctb",
            name="cent",
        ),
        migrations.AddField(
            model_name="customertb",
            name="cent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="voc.centertb",
            ),
            preserve_default=False,
        ),
    ]
