# Generated by Django 4.2.2 on 2023-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0007_remove_voctb_cent_customertb_cent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertb",
            name="tm_judge",
            field=models.CharField(
                default=None, max_length=300, verbose_name="TM messages"
            ),
        ),
    ]
