# Generated by Django 4.2.2 on 2023-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_uidtb_cent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uidtb",
            old_name="cent_id",
            new_name="cent",
        ),
    ]
