# Generated by Django 4.2.2 on 2023-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_cent_id_uidtb_cent"),
    ]

    operations = [
        migrations.CreateModel(
            name="APITB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="KT API Callback Key")),
            ],
        ),
    ]
