# Generated by Django 4.2.2 on 2023-07-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_apitb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apitb",
            old_name="count",
            new_name="key_count",
        ),
    ]
