# Generated by Django 4.2.2 on 2023-06-28 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("voc", "0007_remove_voctb_cent_customertb_cent"),
        (
            "construction",
            "0002_constructioncalltb_remove_constructiontb_cstr_desc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="constructiontb",
            name="cstrcall",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="construction.constructioncalltb",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="constructiontb",
            name="receipt",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date added",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="constructiontb",
            name="cent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="voc.centertb"
            ),
        ),
    ]
