# Generated by Django 4.2.2 on 2023-07-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0004_remove_constructiontb_cent_constructioncalltb_cent"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructiontb",
            name="cstr_manager",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="construction manager"
            ),
        ),
        migrations.AlterField(
            model_name="constructiontb",
            name="receipt",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 3, 14, 18, 56, 343962),
                verbose_name="date added",
            ),
        ),
    ]
