# Generated by Django 4.2.2 on 2023-07-03 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0005_constructiontb_cstr_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructiontb",
            name="receipt",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 3, 14, 20, 4, 163807),
                verbose_name="date added",
            ),
        ),
    ]
