# Generated by Django 4.2.2 on 2023-07-03 14:44

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0007_alter_constructiontb_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructiontb",
            name="receipt",
            field=models.DateTimeField(
                default=timezone.now(),
                verbose_name="date added",
            ),
        ),
    ]
