# Generated by Django 4.2.2 on 2023-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("construction", "0009_alter_constructiontb_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constructiontb",
            name="cstr_manager",
        ),
        migrations.RemoveField(
            model_name="constructiontb",
            name="cstr_num",
        ),
        migrations.AddField(
            model_name="constructioncalltb",
            name="cstr_manager",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="construction manager"
            ),
        ),
        migrations.AddField(
            model_name="constructioncalltb",
            name="cstr_num",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="company tel number"
            ),
        ),
        migrations.AlterField(
            model_name="constructioncalltb",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="uploaded date"),
        ),
    ]
