# Generated by Django 4.2.2 on 2023-07-03 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0006_alter_constructiontb_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructiontb",
            name="receipt",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 3, 14, 42, 46, 93260),
                verbose_name="date added",
            ),
        ),
    ]
