# Generated by Django 4.2.2 on 2023-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardtb",
            name="id",
        ),
        migrations.AlterField(
            model_name="boardtb",
            name="brd_id",
            field=models.CharField(
                max_length=30,
                primary_key=True,
                serialize=False,
                verbose_name="board ID",
            ),
        ),
    ]
