# Generated by Django 4.2.2 on 2023-06-28 11:23

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_boardtb_brd_content_alter_boardtb_brd_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="board/media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "txt",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="업로드된 파일",
            ),
        ),
    ]
